### ISSUE TITLE
registration problem

### ISSUE THREAD

**Issue by reaper7** [Crewski/HANotify#3]
I have HA 0.78.3 and I can't register from android app :(
I pass url as is in http config: _https://my.extdomain.net:8123_
and enter pass: _MySecretPass_
I still get "Something went wrong"
but with this parameters I can view HA panel from android webbrowsers
P.S. I use self signed certificate on HA

config homeassistant:
```
homeassistant:
  name: MyHome
  latitude: 12.637310
  longitude: 34.182883
  elevation: 150
  unit_system: metric
  time_zone: Europe/Warsaw
  customize: !include includes/customize.yaml
  auth_providers:
    - type: homeassistant
    - type: legacy_api_password
    - type: trusted_networks
```

config http:
```
api_password: MySecretPass
base_url: my.extdomain.net:8123
ssl_certificate: /home/pi/.homeassistant/certificate.pem
ssl_key: /home/pi/.homeassistant/privkey.pem
cors_allowed_origins:
  - https://google.com
  - https://www.home-assistant.io
use_x_forwarded_for: True
trusted_proxies:
  - 127.0.0.1
  - ::1
  - 192.168.0.254
trusted_networks:
  - 127.0.0.1
  - ::1
  - 192.168.0.0/24
```

config notify:
```
- name: android
  platform: fcm-android
```
